#!/usr/bin/env python3
"""Bakes every sculpture of KORIUM UNIVERSE: SDF -> marching cubes -> QEM -> OBJ + JSON.

  /opt/korium-py/bin/python tools/sculpt/bake_all.py                # all, final quality
  /opt/korium-py/bin/python tools/sculpt/bake_all.py --only hand_left --quick --out /tmp/x

Output is deterministic (same bytes on every run with the same numpy/scipy/scikit-image).
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
import time

for _var in ("OPENBLAS_NUM_THREADS", "OMP_NUM_THREADS", "MKL_NUM_THREADS"):
    os.environ.setdefault(_var, "1")  # single-threaded BLAS: bit-identical output

import numpy as np  # noqa: E402

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import giant_hands  # noqa: E402
import miku  # noqa: E402
from mesher import bake, log, write_obj  # noqa: E402
from sdf import evaluate, gradient  # noqa: E402

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
OUT_DIR = os.path.join(ROOT, "assets", "meshes")
FORMAT_VERSION = 1


def tight_bounds(f, lo, hi, h, pad):
    """Bounding box of the solid (d < 0) found on a coarse grid, padded."""
    lo, hi = np.asarray(lo, float), np.asarray(hi, float)
    axes = [np.arange(lo[i], hi[i] + h, h) for i in range(3)]
    g = np.stack(np.meshgrid(*axes, indexing="ij"), axis=-1).reshape(-1, 3)
    d = evaluate(f, g)
    inside = g[d < h]
    assert len(inside), "empty shape"
    b_lo, b_hi = inside.min(axis=0) - pad, inside.max(axis=0) + pad
    assert np.all(b_lo > lo) and np.all(b_hi < hi), f"search box too small: {b_lo} {b_hi}"
    return b_lo, b_hi


def r(v, n=4):
    """Rounded plain list for JSON (deterministic, no -0.0)."""
    return [round(float(x), n) + 0.0 for x in np.asarray(v, float).reshape(-1)]


TARGETS = {
    "hand_left": dict(module="hands", side="left", h=0.022, faces=58000,
                      ao=(0.06, 0.14, 0.3, 0.55, 0.9, 1.4), search=((-9, -6, -6), (7, 6, 6))),
    "hand_right": dict(module="hands", side="right", h=0.022, faces=58000,
                       ao=(0.06, 0.14, 0.3, 0.55, 0.9, 1.4), search=((-7, -6, -6), (9, 6, 6))),
    "miku_body": dict(module="miku", h=0.0072, faces=118000,
                      ao=(0.012, 0.03, 0.07, 0.14, 0.26, 0.45), search=((-2, -4.8, -2.4), (2, 2.4, 2.2))),
}


def build_target(name, spec):
    if spec["module"] == "hands":
        f, anchors = giant_hands.build(spec["side"])
        return f, anchors
    return miku.build()


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", action="append", help="target name (repeatable)")
    ap.add_argument("--quick", action="store_true", help="coarse preview bake (2.2x spacing)")
    ap.add_argument("--out", default=OUT_DIR)
    args = ap.parse_args(argv)
    os.makedirs(args.out, exist_ok=True)
    names = args.only or list(TARGETS)
    for name in names:
        spec = TARGETS[name]
        t0 = time.time()
        f, anchors = build_target(name, spec)
        h = spec["h"] * (2.2 if args.quick else 1.0)
        faces = spec["faces"] // (3 if args.quick else 1)
        lo, hi = tight_bounds(f, *spec["search"], h=spec["h"] * 6, pad=spec["h"] * 12)
        extra = miku.bake_spec() if spec["module"] == "miku" else {}
        kw = {"importance": extra["importance"]} if "importance" in extra else None
        res = bake(f, lo, hi, h, faces, spec["ao"], warp=extra.get("warp"), decimate_kw=kw)
        V, N, C, F = res["V"], res["N"], res["C"], res["F"]
        st = res["stats"]
        assert st["boundary_edges"] == 0 and st["nonmanifold_edges"] == 0, st
        assert st["components"] == 1, st
        meta = make_meta(name, spec, f, anchors, V, st, h, args.quick)
        header = (f"KORIUM UNIVERSE sculpture '{name}' -- generated by tools/sculpt/bake_all.py\n"
                  f"v x y z r g b: vertex colour = ambient occlusion (linear, 1 = open)\n"
                  f"{st['vertices']} vertices, {st['triangles']} triangles, grid h={h:.4f}")
        size = write_obj(os.path.join(args.out, f"{name}.obj"), V, N, C, F, header)
        with open(os.path.join(args.out, f"{name}.json"), "w", encoding="ascii") as fh:
            fh.write(json.dumps(meta, indent=2, sort_keys=True) + "\n")
        with open(os.path.join(args.out, f"{name}.obj"), "rb") as fh:
            digest = hashlib.sha256(fh.read()).hexdigest()[:16]
        log(f"{name}: {size / 1e6:.2f} MB sha256:{digest} ({time.time() - t0:.0f}s)")


def make_meta(name, spec, f, anchors, V, st, h, quick):
    lo, hi = V.min(axis=0), V.max(axis=0)
    meta = {
        "name": name,
        "format_version": FORMAT_VERSION,
        "units": "Godot units",
        "up": "+Y",
        "vertex_color": "RGB = ambient occlusion baked from the SDF (linear, 1 = fully open)",
        "bounds": {"min": r(lo), "max": r(hi), "size": r(hi - lo)},
        "vertices": st["vertices"],
        "triangles": st["triangles"],
        "generator": {"script": "tools/sculpt/bake_all.py", "grid_spacing": round(h, 5),
                      "quick": bool(quick)},
    }
    if spec["module"] == "hands":
        palm = anchors["palm_center"]
        pn = gradient(f, palm[None, :], 0.02)[0]
        tips = anchors["tips"]
        wrist = anchors["wrist_center"]
        meta.update({
            "origin": "palm_center (on the palm surface)",
            "frame": ("fingers -> +X, palm faces +Y, forearm towards -X" if spec["side"] == "left"
                      else "fingers -> -X, palm faces -Y, forearm towards +X"),
            "anchors": {
                "palm_center": r(palm),
                "palm_normal": r(pn),
                "wrist_center": r(wrist),
                "forearm_dir": r(anchors["forearm_dir"]),
                "forearm_end": r(anchors["forearm_end"]),
                "tip_thumb": r(tips["thumb"]),
                "tip_index": r(tips["index"]),
                "tip_middle": r(tips["middle"]),
                "tip_ring": r(tips["ring"]),
                "tip_little": r(tips["little"]),
            },
            "wrist_to_middle_tip": round(float(np.linalg.norm(tips["middle"] - wrist)), 3),
        })
    else:
        meta.update(miku.metadata(f, anchors))
    return meta


if __name__ == "__main__":
    main()
